#!/usr/bin/env python3

import argparse
import csv
from datetime import datetime


VERSION = "MAGFlow report 1.0.0"


def html_header():
    return """<!DOCTYPE html>
<html lang="en">
<head>

<meta charset="UTF-8">

<title>MAGFlow Report</title>

<style>

body{
    font-family:Arial,Helvetica,sans-serif;
    margin:40px;
    background:#f8f9fa;
}

table{
    border-collapse:collapse;
    margin-bottom:30px;
}

th,td{
    border:1px solid #ccc;
    padding:8px;
}

th{
    background:#efefef;
}

h1{
    color:#0b5394;
}

</style>

</head>

<body>

<h1>MAGFlow Report</h1>
"""


def html_footer():

    return f"""

<hr>

<p>

Generated by MAGFlow<br>

Generated on {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}<br>

Report version {VERSION}

</p>

</body>

</html>
"""


def main():

    parser = argparse.ArgumentParser()

    parser.add_argument("--summary", required=True)

    parser.add_argument("--output", required=True)

    args = parser.parse_args()

    html = ""

    html += html_header()

    html += "<h2>Hello MAGFlow!</h2>"

    html += "<p>This is the first MAGFlow HTML report.</p>"

    html += html_footer()

    with open(args.output, "w") as out:

        out.write(html)


if __name__ == "__main__":
    main()
